-- Function: "SIMA018".obtener_ejecucion(character, character, character, character, character)

-- DROP FUNCTION "SIMA018".obtener_ejecucion(character, character, character, character, character);

CREATE OR REPLACE FUNCTION "SIMA018".obtener_ejecucion(
    codigopre character,
    perdes character,
    perhas character,
    anno character,
    tipo character)
  RETURNS numeric AS
$BODY$
DECLARE
MONPRC NUMERIC(32,2);
MONCOM NUMERIC(32,2);
MONCAU NUMERIC(32,2);
MONPAG NUMERIC(32,2);
MONTRN NUMERIC(32,2);
MONTRA NUMERIC(32,2);
MONADI NUMERIC(32,2);
MONDIS NUMERIC(32,2);
BEGIN

IF TIPO='PRC' THEN
SELECT SUM(MONTO) INTO MONPRC FROM
(select COALESCE(SUM(B.MONIMP),0) AS MONTO
from CPPRECOM A,CPIMPPRC B
WHERE A.ANOPRC=ANNO
AND TO_CHAR(A.FECPRC,'MM')<=PERHAS
AND TO_CHAR(A.FECPRC,'MM')>=PERDES
AND A.REFPRC=B.REFPRC
AND B.CodPre LIKE CODIGOPRE||'%'
AND (B.STAIMP<>'N'
OR (B.STAIMP='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY')))) --PRECOMPROMISOS
UNION ALL
select COALESCE(SUM(C.MONAJU*(-1)),0) AS MONTO
from CPPRECOM A,CPAJUSTE B,CPMOVAJU C,CPDOCAJU D
WHERE A.ANOPRC=ANNO
AND TO_CHAR(B.FECAJU,'MM')<=PERHAS
AND TO_CHAR(B.FECAJU,'MM')>=PERDES
AND A.REFPRC=B.REFERE
AND B.TIPAJU=D.TIPAJU
AND D.REFIER='P'
AND B.REFAJU=C.REFAJU
AND C.CodPre Like CODIGOPRE||'%'
AND (C.STAMOV<>'N'
OR (C.STAMOV='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY')))) --AJUSTES A PRECOMPROMISOS
UNION ALL
select COALESCE(SUM(B.MONIMP),0) AS MONTO
from CPCOMPRO A,CPIMPCOM B,CPDOCCOM C
WHERE A.ANOCOM=ANNO
AND TO_CHAR(A.FECCOM,'MM')<=PERHAS
AND TO_CHAR(A.FECCOM,'MM')>=PERDES
AND A.TIPCOM=C.TIPCOM
AND C.AFEPRC='S'
AND A.REFCOM=B.REFCOM
AND B.CodPre Like CODIGOPRE||'%'
AND (B.STAIMP<>'N'
OR (B.STAIMP='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY')))) --COMPROMISOS QUE PRECOMPROMETEN
UNION ALL
select COALESCE(SUM(C.MONAJU*(-1)),0) AS MONTO
from CPCOMPRO A,CPAJUSTE B,CPMOVAJU C,CPDOCAJU D,CPDOCCOM E
WHERE A.ANOCOM=ANNO
AND TO_CHAR(B.FECAJU,'MM')<=PERHAS
AND TO_CHAR(B.FECAJU,'MM')>=PERDES
AND A.TIPCOM=E.TIPCOM
AND E.AFEPRC='S'
AND A.REFCOM=B.REFERE
AND B.TIPAJU=D.TIPAJU
AND D.REFIER='C'
AND B.REFAJU=C.REFAJU AND
C.CodPre Like CODIGOPRE||'%'
AND (C.STAMOV<>'N'
 OR (C.STAMOV='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY')))) -- AJUSTES A COMPROMISOS QUE PRECOMPROMETEN
UNION ALL
select COALESCE(SUM(B.MONIMP),0) AS MONTO
from CPCAUSAD A,CPIMPCAU B,CPDOCCAU C
WHERE A.ANOCAU=ANNO
AND TO_CHAR(A.FECCAU,'MM')<=PERHAS
AND TO_CHAR(A.FECCAU,'MM')>=PERDES
AND A.TIPCAU=C.TIPCAU
AND C.AFEPRC='S'
AND A.REFCAU=B.REFCAU
AND B.CodPre Like CODIGOPRE||'%'
AND (B.STAIMP<>'N'
OR (B.STAIMP='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY')))) --CAUSADOS QUE PRECOMPROMETEN
UNION ALL
select COALESCE(SUM(C.MONAJU*(-1)),0) AS MONTO
from CPCAUSAD A,CPAJUSTE B,CPMOVAJU C,CPDOCAJU D,CPDOCCAU E
WHERE A.ANOCAU=ANNO
AND TO_CHAR(B.FECAJU,'MM')<=PERHAS
AND TO_CHAR(B.FECAJU,'MM')>=PERDES
AND A.TIPCAU=E.TIPCAU
AND E.AFEPRC='S'
AND A.REFCAU=B.REFERE
AND B.TIPAJU=D.TIPAJU
AND D.REFIER='A'
AND B.REFAJU=C.REFAJU
AND C.CodPre Like CODIGOPRE||'%'
AND (C.STAMOV<>'N'
OR (C.STAMOV='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY')))) --AJUSTES A CAUSADOS QUE PRECOMPROMETEN
UNION ALL
select COALESCE(SUM(B.MONIMP),0) AS MONTO
from CPPAGOS A,CPIMPPAG B,CPDOCPAG C
WHERE A.ANOPAG=ANNO
AND TO_CHAR(A.FECPAG,'MM')<=PERHAS
AND TO_CHAR(A.FECPAG,'MM')>=PERDES
AND A.TIPPAG=C.TIPPAG
AND C.AFEPRC='S'
AND A.REFPAG=B.REFPAG
AND B.CodPre Like CODIGOPRE||'%'
AND (B.STAIMP<>'N'
OR (B.STAIMP='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY')))) --PAGADOS QUE PRECOMPROMETEN
UNION ALL
select COALESCE(SUM(C.MONAJU*(-1)),0) AS MONTO
from CPPAGOS A,CPAJUSTE B,CPMOVAJU C,CPDOCAJU D,CPDOCPAG E
WHERE A.ANOPAG=ANNO
AND TO_CHAR(B.FECAJU,'MM')<=PERHAS
AND TO_CHAR(B.FECAJU,'MM')>=PERDES
AND A.TIPPAG=E.TIPPAG
AND E.AFEPRC='S'
AND A.REFPAG=B.REFERE
AND B.TIPAJU=D.TIPAJU
AND D.REFIER='G'
AND B.REFAJU=C.REFAJU
AND C.CodPre Like CODIGOPRE||'%'
AND (C.STAMOV<>'N'
OR (C.STAMOV='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))))) --AJUSTES A PAGADOS QUE PRECOMPROMETEN
AS PRECOM;


RETURN(MONPRC);
END IF;

IF TIPO='COM' THEN
SELECT SUM(MONTO) INTO MONCOM FROM
(select COALESCE(SUM(B.MONIMP),0) AS MONTO
from CPCOMPRO A,CPIMPCOM B
WHERE A.ANOCOM=ANNO
AND TO_CHAR(A.FECCOM,'MM')<=PERHAS
AND TO_CHAR(A.FECCOM,'MM')>=PERDES
AND A.REFCOM=B.REFCOM AND
B.CodPre Like CODIGOPRE||'%'
AND (B.STAIMP<>'N'
OR (B.STAIMP='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))))
UNION ALL
select COALESCE(SUM(C.MONAJU*(-1)),0) AS MONTO
from CPCOMPRO A,CPAJUSTE B,CPMOVAJU C,CPDOCAJU D
WHERE A.ANOCOM=ANNO
AND TO_CHAR(B.FECAJU,'MM')<=PERHAS
AND TO_CHAR(B.FECAJU,'MM')>=PERDES
AND A.REFCOM=B.REFERE
AND B.TIPAJU=D.TIPAJU
AND D.REFIER='C'
AND B.REFAJU=C.REFAJU
AND C.CodPre Like CODIGOPRE||'%'
AND (C.STAMOV<>'N'
OR (C.STAMOV='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))))
UNION ALL
select COALESCE(SUM(B.MONIMP),0) AS MONTO
from CPCAUSAD A,CPIMPCAU B,CPDOCCAU C
WHERE A.ANOCAU=ANNO
AND TO_CHAR(A.FECCAU,'MM')<=PERHAS
AND TO_CHAR(A.FECCAU,'MM')>=PERDES
AND A.TIPCAU=C.TIPCAU
AND C.AFECOM='S'
AND A.REFCAU=B.REFCAU
AND B.CodPre Like CODIGOPRE||'%'
AND (B.STAIMP<>'N'
OR (B.STAIMP='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))))
UNION ALL
select COALESCE(SUM(C.MONAJU*(-1)),0) AS MONTO
from CPCAUSAD A,CPAJUSTE B,CPMOVAJU C,CPDOCAJU D,CPDOCCAU E
WHERE A.ANOCAU=ANNO
AND TO_CHAR(B.FECAJU,'MM')<=PERHAS
AND TO_CHAR(B.FECAJU,'MM')>=PERDES
AND A.TIPCAU=E.TIPCAU
AND E.AFECOM='S'
AND A.REFCAU=B.REFERE
AND B.TIPAJU=D.TIPAJU
AND D.REFIER='A'
AND B.REFAJU=C.REFAJU
AND C.CodPre Like CODIGOPRE||'%'
AND (C.STAMOV<>'N'
OR (C.STAMOV='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))))
UNION ALL
select COALESCE(SUM(B.MONIMP),0) AS MONTO
from CPPAGOS A,CPIMPPAG B,CPDOCPAG C
WHERE A.ANOPAG=ANNO
AND TO_CHAR(A.FECPAG,'MM')<=PERHAS
AND TO_CHAR(A.FECPAG,'MM')>=PERDES
AND A.TIPPAG=C.TIPPAG
AND C.AFECOM='S'
AND A.REFPAG=B.REFPAG
AND B.CodPre Like CODIGOPRE||'%'
AND (B.STAIMP<>'N'
OR (B.STAIMP='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))))
UNION ALL
select COALESCE(SUM(C.MONAJU*(-1)),0) AS MONTO
from CPPAGOS A,CPAJUSTE B,CPMOVAJU C,CPDOCAJU D,CPDOCPAG E
WHERE A.ANOPAG=ANNO
AND TO_CHAR(B.FECAJU,'MM')<=PERHAS
AND TO_CHAR(B.FECAJU,'MM')>=PERDES
AND A.TIPPAG=E.TIPPAG
AND E.AFECOM='S'
AND A.REFPAG=B.REFERE
AND B.TIPAJU=D.TIPAJU
AND D.REFIER='G'
AND B.REFAJU=C.REFAJU
AND C.CodPre Like CODIGOPRE||'%'
AND (C.STAMOV<>'N'
OR (C.STAMOV='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))))) AS COMPRO;
RETURN(MONCOM);
END IF;


IF TIPO='CAU' THEN
SELECT SUM(MONTO) INTO MONCAU FROM
(select COALESCE(SUM(B.MONIMP),0) AS MONTO
from CPCAUSAD A,CPIMPCAU B
WHERE A.ANOCAU=ANNO
AND TO_CHAR(A.FECCAU,'MM')<=PERHAS
AND TO_CHAR(A.FECCAU,'MM')>=PERDES
AND A.REFCAU=B.REFCAU
AND B.CodPre Like CODIGOPRE||'%'
AND (B.STAIMP<>'N'
OR (B.STAIMP='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))))
UNION ALL
select COALESCE(SUM(C.MONAJU*(-1)),0) AS MONTO
from CPCAUSAD A,CPAJUSTE B,CPMOVAJU C,CPDOCAJU D
WHERE A.ANOCAU=ANNO
AND TO_CHAR(B.FECAJU,'MM')<=PERHAS
AND TO_CHAR(B.FECAJU,'MM')>=PERDES
AND A.REFCAU=B.REFERE
AND B.TIPAJU=D.TIPAJU
AND D.REFIER='A'
AND B.REFAJU=C.REFAJU
AND C.CodPre Like CODIGOPRE||'%'
AND (C.STAMOV<>'N'
OR (C.STAMOV='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))))
UNION ALL
select COALESCE(SUM(B.MONIMP),0) AS MONTO
from CPPAGOS A,CPIMPPAG B,CPDOCPAG C
WHERE A.ANOPAG=ANNO
AND TO_CHAR(A.FECPAG,'MM')<=PERHAS
AND TO_CHAR(A.FECPAG,'MM')>=PERDES
AND A.TIPPAG=C.TIPPAG
AND C.AFECAU='S'
AND A.REFPAG=B.REFPAG
AND B.CodPre Like CODIGOPRE||'%'
AND (B.STAIMP<>'N'
OR (B.STAIMP='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))))
UNION ALL
select COALESCE(SUM(C.MONAJU*(-1)),0) AS MONTO
from CPPAGOS A,CPAJUSTE B,CPMOVAJU C,CPDOCAJU D,CPDOCPAG E
WHERE A.ANOPAG=ANNO
AND TO_CHAR(B.FECAJU,'MM')<=PERHAS
AND TO_CHAR(B.FECAJU,'MM')>=PERDES
AND A.TIPPAG=E.TIPPAG
AND E.AFECAU='S'
AND A.REFPAG=B.REFERE
AND B.TIPAJU=D.TIPAJU
AND D.REFIER='G'
AND B.REFAJU=C.REFAJU
AND C.CodPre Like CODIGOPRE||'%'
AND (C.STAMOV<>'N'
OR (C.STAMOV='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))))) AS CAUSAD;
RETURN(MONCAU);
END IF;

IF TIPO='PAG' THEN
SELECT SUM(MONTO) INTO MONPAG FROM
(select COALESCE(SUM(B.MONIMP),0) AS MONTO
from CPPAGOS A,CPIMPPAG B
WHERE A.ANOPAG=ANNO
AND TO_CHAR(A.FECPAG,'MM')<=PERHAS
AND TO_CHAR(A.FECPAG,'MM')>=PERDES
AND A.REFPAG=B.REFPAG
AND B.CodPre Like CODIGOPRE||'%'
AND (B.STAIMP<>'N'
OR (B.STAIMP='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))))
UNION ALL
select COALESCE(SUM(C.MONAJU*(-1)),0) AS MONTO
from CPPAGOS A,CPAJUSTE B,CPMOVAJU C,CPDOCAJU D
WHERE A.ANOPAG=ANNO
AND TO_CHAR(B.FECAJU,'MM')<=PERHAS
AND TO_CHAR(B.FECAJU,'MM')>=PERDES
AND A.REFPAG=B.REFERE
AND B.TIPAJU=D.TIPAJU
AND D.REFIER='G'
AND B.REFAJU=C.REFAJU
AND C.CodPre Like CODIGOPRE||'%'
AND (C.STAMOV<>'N'
OR (C.STAMOV='N'
AND A.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))))) AS PAGADO;
RETURN(MONPAG);
END IF;

IF TIPO='TRA' THEN
SELECT SUM(A.MONMOV) INTO MONTRA
         FROM CPMOVTRA A,CPTRASLA B
         WHERE PERTRA<=PERHAS
         AND   PERTRA>=PERDES
     AND A.REFTRA=B.REFTRA
     AND A.CodDES Like CODIGOPRE||'%'
     AND (STAMOV<>'N'
          OR (STAMOV='N'
          AND B.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))));
RETURN(MONTRA);
END IF;

IF TIPO='TRN' THEN
SELECT SUM(A.MONMOV) INTO MONTRN
         FROM CPMOVTRA A,CPTRASLA B
         WHERE PERTRA<=PERHAS
         AND   PERTRA>=PERDES
     AND A.REFTRA=B.REFTRA
     AND A.CodORI Like CODIGOPRE||'%'
     AND (STAMOV<>'N'
              OR (STAMOV='N'
          AND B.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))));
RETURN(MONTRN);
END IF;

IF TIPO='ADI' THEN
SELECT SUM(A.MONMOV) INTO MONADI
     FROM CPMOVADI A,CPADIDIS B
     WHERE TO_CHAR(B.FECADI,'MM')<=PERHAS
   AND TO_CHAR(B.FECADI,'MM')>=PERDES
     AND B.ANOADI=ANNO
     AND B.ADIDIS='A'
     AND A.REFADI=B.REFADI
     AND A.CodPRE Like CODIGOPRE||'%'
     AND (STAMOV<>'N'
          OR (STAMOV='N'
          AND B.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))));
RETURN(MONADI);
END IF;

IF TIPO='DIS' THEN
SELECT SUM(A.MONMOV) INTO MONDIS
         FROM CPMOVADI A,CPADIDIS B
     WHERE TO_CHAR(B.FECADI,'MM')<=PERHAS
   AND TO_CHAR(B.FECADI,'MM')>=PERDES
     AND B.ANOADI=ANNO
     AND B.ADIDIS='D'
     AND A.REFADI=B.REFADI
     AND A.CodPRE Like CODIGOPRE||'%'
     AND (STAMOV<>'N'
          OR (STAMOV='N'
          AND B.FECANU>LAST_DAY(TO_DATE(PERHAS||'/'||ANNO,'MM/YYYY'))));
   RETURN(MONDIS);
END IF;

END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION "SIMA018".obtener_ejecucion(character, character, character, character, character)
  OWNER TO postgres;